### ISSUE TITLE
助教

### ISSUE THREAD

**Issue by yanlong658** [tangxiangshi/homework#1]
#define PI 3.1415926f
建議使用C++內建的 M_PI
會比較好

**Comment by tangxiangshi** [comment]
OK 下次用这个 之前不太知道





------------------ 原始邮件 ------------------
发件人: yanlong658 <notifications@github.com&gt;
发送时间: 2020年4月6日 11:47
收件人: tangxiangshi/homework <homework@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[tangxiangshi/homework] 助教 (#1)





 
#define PI 3.1415926f
 建議使用C++內建的 M_PI
 會比較好
